# Generated by Django 2.2 on 2020-03-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
